### PR TITLE
add zone-update subcommand

### PR DESCRIPTION
**Pull request by jrwren**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions.

### Description of the Change

zone-update, a lot like zone-create.

### Why Should This Be In The Package?

for #46 

### Benefits

Can update.

### Possible Drawbacks

Can update.

### Verification Process

None.

### CODE REVIEW

**Comment by mdb** [comment]
@jrwren Thanks so much for this! I have 2 thoughts on initial review:

1. Would you mind writing some tests for this?
2. The original issue ( #46 ) specifies that the command should support a `--json` flag, the value of which should be the full zone JSON, similar to how `zone-create` works. Would you mind adding this functionality as well?

Thanks!

**Comment by jrwren** [comment]
Tests to me, would mean _test.go files, but I do not see any in this package, which is why I didn't write any in the first place. Now I see a fixtures directory, but I have no idea how to write a test there. Can someone walk me through it? Incidentally, it would be nice if `CONTRIBUTING.md` mentioned standards for tests.

AFAIK, the --json flag is global and is handled by 
```
+       if c.GlobalString(outputFlag) == "json" {
+               return printJSON(updated)
+       }
```

But maybe I misunderstand the response there and the desired output.

**Comment by mdb** [comment]
> Can someone walk me through it?

@jrwren Sure! The tests are more like "acceptance" tests that exercise the end-result compiled `vinyldns` CLI (rather than `*_test.go`-style "unit" tests that validate specific source code business logic).

The tests live in the [tests](https://github.com/vinyldns/vinyldns-cli/tree/master/tests) directory and, specifically, the `tests/vinyldns_tests.bats` file. The tests are authored in [bats](https://github.com/sstephenson/bats) and exercise `vinyldns-cli` functionality by using a compiled `vinyldns` CLI to run various commands against a local, `docker-compose`'d VinylDNS API. These tests are run as part of the `make` [tasks](https://github.com/vinyldns/vinyldns-cli/blob/master/Makefile#L15). To start a local VinylDNS API and run the tests, you can run `make`. Hopefully, the existing tests in `tests/vinyldns_tests.bats` serve as useful examples to emulate.

> AFAIK, the --json flag is global and is handled by...

☝️ This is the `--output` flag, which is global. Its value can be `json` but defaults to `table`. However, many of the `*-create` commands accept a `--json` flag that accepts a VinylDNS JSON string representing the model to create. 

For example, `group-create` accepts [such a `--json` string](https://github.com/vinyldns/vinyldns-cli/blob/master/src/cli.go#L84-L90). The `--json` flag's value should be a VinylDNS [group JSON string](https://www.vinyldns.io/api/create-group.html). The command uses the string to [create a group](https://github.com/vinyldns/vinyldns-cli/blob/master/src/groups.go#L83-L89). This pattern is common throughout `vinyldns-cli` and it would be useful to emulate it for `update-zone` (while also providing users the option of using the existing flags, as you've done thus far in this pull request).

> Incidentally, it would be nice if `CONTRIBUTING.md` mentioned standards for tests.

Thanks for pointing this out. I agree and have created [this issue](https://github.com/vinyldns/vinyldns-cli/issues/73). While the `README.md` mentions [tests should accompany new features](https://github.com/vinyldns/vinyldns-cli#development), the `CONTRIBUTING.md` fails to mention it.

**Comment by mdb** [comment]
I'm going to close this, as it was implemented via PR #86 .

**Pull request closed without merging**
